### ISSUE TITLE
invenio-assets: CI error when updating to v1.3.1

### ISSUE THREAD

**Issue by ItIsJordan** [HEPData/hepdata#542]
When updating to v1.3.1 (currently using 1.3.0) of invenio-assets, the **setup npm and build assets** section of the CI fails with the error **Error: Cannot find module 'ajv/dist/compile/codegen'**.

**Comment by GraemeWatt** [comment]
Problem is avoided by updating to `invenio-assets` v2.0.0 (PR #555).
